### PR TITLE
Added Changelog

### LINKED ISSUE #17: Add a changelog
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

A changelog to see all changes between version.
Would be nice to write it according the 'standard' defined here https://keepachangelog.com
I'll get to this tonight

### PR DESCRIPTION
**Pull request by Baklap4**
### What does this PR do?

* Adds a changelog to the project.
    * This changelog will document all relevant changes for the user between versions.
* Updated `Pull request template` to ensure the changelog is correctly kept up to date.

### Closes Issue(s)

* Closes #17 

### Motivation

A changelog keeps track of all changes in the program. This way users are always up to date with what will be in the next version, and what was in the previous versions. Users are also able to easily check the differences between those versions.

### More

- [X] Added/updated documentation
- [X] Updated changelog with all relevant info up till now.

### CODE REVIEW

**Comment by basisbit** [comment]
changelog tends to be somewhat of a religion thing. Bunch of smaller projects just use git commit log during development and then whenever they tag a version/release in github, they read the commit log to then write a changelog / news message.
Changelog files in the repo tend to be outdated and/or forgotten even in some bigger projects.

I'd like to...
 - [ ] get some more opinions from other project maintainers 
 - [ ] and will ask some friends about best practices, if you are ok with that.
 - [ ] Maybe @brianch, @AlexanderS or @kamischi want to comment on this?

**Comment by basisbit** [comment]
Also, I'd definitely vote for not mentioning any contributor names in the changelog. Mentioning people in such documents tends to cause inter-human issues or someone might have different opinions on who did what and who should get what kudos,.... We should try to keep this as objective as possible. @Baklap4 what is your opinion on this?

**Comment by Baklap4** [comment]
> Bunch of smaller projects just use git commit log during development and then whenever they tag a version/release in github, they read the commit log to then write a changelog / news message.

That's why there's an unreleased section within the changelog.
Beside this section there's also a checkbox within the Pullrequest format to enforce the coder to alter the changelog if it's something involving the end-user.

As for this changelog i've took the template from https://keepachangelog.com/ Which is trying to be the defacto standard regarding changelogs.

I myself find it pretty useful to see who added what feature in what release, and even be able to track breaking changes in one glimpse.

Yes this is a small repo, however this does not mean we should slack, it's exactly around this time to get these things straightened out and create a quality-standard for the project

> I'd definitely vote for not mentioning any contributor names in the changelog
As the changes to the changelog will be affected by each PR we can easily see who's involved in whatever what. IMHO the coders should be tagged and deserve an honorable mention. Besides we're linking back to the PR, so everyone is able to tell clearly who did what. As for the tags, this would only include the actual coders, not the people reviewing it or such. Yes they helped maintaining the quality yet they didn't actively develop anything in these PR's. If they did, they'll get a mention aswell

**Comment by Baklap4** [comment]
Closed as per statement on gitter:

>basisbit @basisbit 07:52
After sone thinking and talking with other project maintainers, I made some decisions: UltraStar Play is a project in its very early stage of development with lots of experimenting with new ideas and making decisions based on what I want for this project to be. Also, there are only ~ 1.5 to 3 people currently actively contributing to the project. Thus, nodejs's liberal contribution policy or apache foundation's meritocracy model will not result in the fast project progress that I wanted for this project to happen. Once some more governance documentation is written, more code is actually done and some actually usable game state is achieved, a liberal contribution policy like the one from ffmpeg or nodejs will be suitable. For now, this project will be governed more or less in a BDFL style like the Python project -> open discussions but final dicisions done by main project maintainer. Some new decidions which I will soon add to the contributing.md / other docs: no changelog file within the project (a wiki page will be used for roadmap / upcoming release, github release description will be used for documenting each released version based on what was written in the wiki page), no copyright/license-header or similar in the code files (that is what the license.md and similar files are for), year.month.* will be used for release version numbers (to keep any discussions about minor or major version jumps to almost zero) - not yet decided if it will be 2018.x.y or 18.x.y (feel free to comment). The wiki will be used for users targeting documentation. The main git repo will be used for developers targeting documentation. The game will mainly target casual gamers, thus please try to avoid feature creep and try to not add hundreds of settings in the default UI - there already exists performous for those who want all the features.

**Pull request closed without merging**
