### PR TITLE
new version notification

### PR DESCRIPTION
**Pull request by achimmihca**
### What does this PR do?

- Implement an update notification as suggested in #127.
    - The file with version and build info is called "version.properties.txt" because it is a properties file but Unity only handles txt file extension as normal TextAsset.
Note that the naming scheme of the release version is not strictly dictated. Stuff like "1.2.3", "2017.04+", "2020-04-10", would all work.

- A build time-stamp (yyMMddHHmm) is automatically set in the version file. The version and build time-stamp are shown in the MainScene. However, the build time-stamp is only shown for debug builds to differentiate builds of the same release in development (including now, where there is no release yet).

    - I assume that a granularity of minutes is sufficient in the time-stamp because a built takes about a minute. I assume that two digits for the year is sufficient, because 80 years is a very long time for such an open-source project.

- I just noticed that I also removed the UI stuff for "Show Preview in Song Select" option from GraphicsOptionsScene. It is not needed anymore because the song preview is working really well by now.

### Closes Issue(s)

#127

### Additional Notes

- We have to check if setting the build time-stamp also works when built by Travis CI. It is implemented using the IPreprocessBuildWithReport interface of Unity.
- When the version file has found its place in the repo, then the URL in the NewVersionChecker has to be updated. At the moment it points to a localhost address.

### CODE REVIEW

**Comment by achimmihca** [comment]
2020-04-26 19_30_34-UltraStar Play - MainScene - PC, Mac   Linux Standalone - Unity 2019 2 0f1 Perso

**Comment by achimmihca** [comment]
Only the build of MacOS failed. Is the MacOS build new?

**Comment by basisbit** [comment]
macOS build fails occasionally for unknown reasons for various projects. I just restarted it

**Comment by basisbit** [comment]
Could you please add a VERSION file to this repository here and then change remoteVersionFileUrl to the raw file here in the master branch in this repo?

**Comment by achimmihca** [comment]
I renamed the file to VERSION.txt and moved it to the root Asset folder. The txt extension is needed for Unity to recognize it as a TextAsset. And it must be placed in the Asset folder for this as well.

I also changed the remoteVersoinFileUrl such that it points to the address where the file will be located as soon as this PR has been merged.

**Pull request merged**
