### PR TITLE
Reintegrate Melody Mania up to 2024-10-06

### LINKED ISSUE #420: Setting for the range of Note Display Mode
Issue type: Feature request

### Actual behavior

Currently, when using any Note Display Mode, the notes have a limited range of pitch.
This causes notes outside of that range to wrap around, making it confusing to understand if
the next note is higher or lower.

For example:
```
This is what it looks like:       This it what is actually happening:
                                  ----0-
-0----                            -0----
------                            ------
----0-                            ------
```

### Expected behaviour

It would be nice to be able to see the full range of notes in a song so that higher notes are always
higher visually. Mabe with a setting that makes the Note Display take up the whole vertical space of the
screen with the range being determined by the range of the song. Alternatively, color coding the notes
by octave could also work as a visual indicator of the actual pitch of the notes.

### LINKED ISSUE #435: Reset test context between Unity Play Mode tests
### Actual behaviour
When running all Play Mode tests in sequence, then there are test failures. But when executed one after another, then they finish successfully.

This is because Unity does not reset the whole application context between Play Mode tests, which seems to be a known shortcoming of Unity (see [forum thread](https://forum.unity.com/threads/running-tests-consecutively.781847/).

This leads to a failing CI pipeline, although the game logic is correct. The test logic is broken.

### Expected behaviour
Executing a test alone or in multiple sequence should not make a difference.

### Implementation Hints
One has to reset all application state manually in a TearDown method, notably DontDestroyOnLoad GameObjects, and static variables.

### LINKED ISSUE #464: Improve Audio Wave Form Rendering in Song Editor
### Actual behaviour
- the audio wave disappears when scrolling in the song editor. After stopping, it is rendered again.

### Expected behaviour
- The audio wave form should always be visible, also during scrolling.

### Implementation
- Currently, the audio wave form is drawn only when the viewport is stable for performance reasons.
    - Current approach to draw the audio wave form: get audio samples for visible viewport, compute audio wave form (i.e. calculating min and max audio sample values in sliding window), draw audio wave form on texture pixel by pixel. All this is done on the CPU
- Needs a prototype to draw an audio wave form more efficiently. Maybe this can be done with a shader.

### LINKED ISSUE #465: Jukebox & Sing Randomization Issue
Issue type: Bug report

### Actual behaviour
In the Jukebox & Sing mod there is a randomization issue when a song finishes playing, the app flashes a bunch of 1 to 2 second clips of songs before landing on the next song.

### Expected behaviour
What is expected in the Jukebox & Sing mod is when a song finishes playing, the app plays the random next song.

### Steps to reproduce

1. Open the melodymania.exe
2. Go to options in the bottom right 
3. Go to Mods menu on the left
4. enable jukebox and sing mod
5. exit the options menu
6. select a song and let it play and finish
7. the mod flashes a bunch of 1 to 2 second clips of songs before landing on the next song.

### Details
End users should not see what songs the system is thinking about playing.(Flashing of 1 to 2 sec clips)
It should just play the next random song.

- Melody Mania version: 1.4.1-beta6
- Windows 11 Home version: 23H2
- if applicable, add a log file

### PR DESCRIPTION
**Pull request by achimmihca**
### What does this PR do?

Reintegrate recent changes from [Melody Mania](https://melodymania.org).

- Contains mostly fixes and refactorings compared to last reintegrate
- Fix the test pipeline by
  - resetting the game state between tests, #435
  - upgrade GitHub Actions

### Closes Issue(s)

close #465
close #464
close #435
close #420

### Motivation

- prepare contributions to UltraStar Play by new developer

### CODE REVIEW

**Comment by achimmihca** [comment]
The pipeline is not working because Unity does not seem to accept the license (same old, same old).


Documentation how to set up the license with the GitHub Actions can be found here: https://game.ci/docs/github/activation

Unfortunately, the instructions do not work. All secrets are in place, but the error remains.

```
Visit https://game.ci/docs/github/activation for more
details on how to set up one of the possible activation strategies.
Error: No valid license activation strategy could be determined. Make sure to provide UNITY_EMAIL, UNITY_PASSWORD, and either a UNITY_SERIAL or UNITY_LICENSE. Otherwise please use UNITY_LICENSING_SERVER.
Error: The process '/usr/bin/docker' failed with exit code 1
```
But UNITY_EMAIL, UNITY_PASSWORD, and UNITY_LICENSE have been set already.

It seems there are also others with this issue.
Unity seems to have changed the way how to activate a personal license.

Before, GameCI had an action to aquire a license request ( https://github.com/marketplace/actions/unity-request-activation-file ). But this is now deprecated

> Please follow the [updated activation steps](https://game.ci/docs/github/activation) for v4 and newer of Unity Actions.

But as I said, the instructions do not work.

- There is an open GitHub issue that suggests to forcibly do the old manual activation ( https://github.com/game-ci/documentation/issues/408 )
  - Note that there is no official support from Unity. This workaround requires tinkering with Unity's website DOM to show hidden UI elements.

- There is a discussion on their Discord that also goes in the direction of doing the old activation
    - https://discord.com/channels/710946343828455455/1138586951604248666

I don't know how to proceed here.
Maybe asking the game-ci folks on Discord may help.

**Comment by basisbit** [comment]
How I previously always got it to work: run the thing locally in a docker container, activate it, get the activation license file content, write that content into a github secret. and have the docker container write that secret into the required license file

**Comment by achimmihca** [comment]
Nevermind, I forgot to expose the new secrets UNITY_EMAIL and UNITY_PASSWORD to the GitHub Actions workflows.

Unity is building the project now, but it seems there are some issues. Will take a look soon.

**Comment by basisbit** [comment]
For Ansis to be able to continue working, we decided to ignore the buidl pipeline requirement for now and merge anyways. Hope this is okay for you.

**Review by basisbit — APPROVED** [review]
lgtm

**Pull request merged**
