### PR TITLE
fix iOS Player Settings

### PR DESCRIPTION
**Pull request by achimmihca**
### What does this PR do?

Fix iOS Player Settings that were mentioned on Gitter.

- added microphoneUsageDescription
- checked "mute other audio sources" to enable Bluetooth microphones

### CODE REVIEW

**Comment by achimmihca** [comment]
2020-11-01 16_13_07-Project Settings

**Comment by basisbit** [comment]
This seems to be a "global" setting for all build targets. Can't this setting be toggled by code if iOS is detected?

**Comment by bohning** [comment]
It is *at least* required for macOS, not sure about iOS (but I would assume so).

**Comment by achimmihca** [comment]
> [PlayerSettings.muteOtherAudioSources](https://docs.unity3d.com/ScriptReference/PlayerSettings-muteOtherAudioSources.html):
This setting is shared between iOS and Android platforms.
Starting with Android Marshmallow (6.0), setting this to false mutes the sound of your Unity application during an incoming phone call (while the phone is ringing).

Seems reasonable to set it to false for Android because the App should mute for an incoming phone call.
However, the PlayerSettings are in UnityEditor namespace and not available in-game. So I guess there is no way to set it for a single platform.

Anyway, it is not be a big issue on Android.
IMO bluetooth mic device for iOS has higher priority.

---
microphoneUsageDescription: I don't think we need this per platform, right?

**Review by basisbit — APPROVED** [review]

**Pull request merged**
