### PR TITLE
UI Toolkit for main OptionsScene and SoundOptionsScene

### PR DESCRIPTION
**Pull request by achimmihca**
### What does this PR do?

This PR re-implements the main OptionsScene (where other option scenes are selected) and the SoundOptionsScene using UIToolkit (#231).

***ItemPicker***
I created a UI control to select items.
- The last implementation was named `ItemSlider`. This new implementation is called `ItemPicker` because "slider" sounds a bit like "scroll bar" to me and I did not find a better name than "picker".
- ItemPicker has multiple parts:
    - ItemPicker.uxml defines the layout/structure of the control
    - ItemPicker.cs registers a factory to instantiate an ItemPicker.
        - It reads some additional XML attributes from the UXML, and instantiates the ItemPicker.uxml file as a child.
        - When using `<ItemPicker />` in another UXML file, then UIToolkit searches for a factory. It will find the ItemPicker.cs factory, which then instantiates ItemPicker.uxml file. Thus, the C# script is first.
             - The child VisualElements that the factory creates are not inside the UXML file. They only exist in the instantiated UIDocument. The UIBuilder shows such elements as greyed out.
                 - This concept is a simiar to a Shadow DOM if you know WebComponents.
             - The ItemPicker.uxml file needs to be instantiated at runtime. Therefor, the file is placed in a Resources special Unity folder.
        - The instantiated ItemPicker itself is a VisualElement. Thus, it can be injected just like other VisualElements.
    - Various `ItemPickerControl<T>` classes, which are generic and define the behaviour of the control (i.e., what happens on button click)
        - starts with `AbstractItemPicker<T>` and goes up to BoolItemPicker, NumberItemPicker, etc.

***SoundOptionsScene***
- I chose the SoundOptionsScene for migration because it was the most simple.
- I added a BackgroundMusicEnabled option for later use (to test BoolItemPicker).
- I added a volume option
    - A new VolumeControl (part of CommonSceneObjects) applies it to all scenes

***OptionsScene***
- Contains a language selection control, which is a ComboBox (in UIToolkit "DropdownField")
    - IMO, language should be one of the first options that can be changed. User can change language to know where the other buttons are leading
- Every button has an image and a label
    - The images are from [Material Design Icons](https://fonts.google.com/icons)
    - The images are SVG graphics. Thankfully, these can be used directly in UIToolkit using com.unity.vectorgraphics package.

***New Options Structure***
- I thought about the structure for options and wanted to tidy up things
    - Therefor, I took a look a other UltraStar and SingStar games for inspiration
- More on this here: #263

***Refined Injection for UIToolkit***
- I refined UniInject a little to inject VisualElements more easily.
- Inject-annotation now has UxmlName and UxmlClass as attribute. These select VisualElements as "#UxmlName" and ".UxmlClass" respectively
    - See [here](https://github.com/achimmihca/UniInject/commit/c2c2cb8924e13f2a8cfa079dd9049a3bdaeed27c).
- Inject-annotation now uses PascalCase instead camelCase for attributes, because these are properties now.
    - Properties enable to hide future changes to the inner workings of annotation parameters.
    - See [here](https://github.com/achimmihca/UniInject/commit/c184f447bb3868d9ecee104901b7c01839967ae2)
- Constants for uxml names and classes are generated, just like the translation keys and InputActions.
    - Generating all these constants is increadibly useful. I autocomplete everything and it is typo-safe 🚀 

### Closes Issue(s)

Nothing yet.
I wanted to make this PR first before changing all other options scenes.

### More
- The new UIToolkit workflow, styles, controls, and injection of VisualElements combined with the generated constants for names and classes are sooo pleasant to use. This is a huge step forward 🚀 ⭐ 🏆

### CODE REVIEW

**Comment by achimmihca** [comment]
2021-11-14 13_02_11-UltraStar Play - OptionsSoundScene - Windows, Mac, Linux - Unity 2021 2 0f1 Pers

---
2021-11-14 13_03_05-UltraStar Play - OptionsScene - Windows, Mac, Linux - Unity 2021 2 0f1 Personal

**Comment by basisbit** [comment]
if I read this correctly, we'll have to add a license file for the apache 2 licensed material design icons. Could you please add such a file? thanks.

**Comment by achimmihca** [comment]
I migrated the AboutScene to UIToolkit to show license info there.
The AboutScene now shows content of txt files that can be iterated (show next/previous txt file).

Besides this, I removed the CreditsScene because it was redundant with AboutScene (credits could be another txt file if needed).

Anyway, I am not a lawyer. Please check if this meets the requirements.

**Comment by achimmihca** [comment]
2021-11-18 18_01_58-UltraStar Play - AboutScene - Android - Unity 2021 2 0f1 Personal _DX11_
--
2021-11-18 18_02_08-UltraStar Play - AboutScene - Android - Unity 2021 2 0f1 Personal _DX11_
--
2021-11-18 18_02_24-UltraStar Play - AboutScene - Android - Unity 2021 2 0f1 Personal _DX11_
--
2021-11-18 18_02_28-UltraStar Play - AboutScene - Android - Unity 2021 2 0f1 Personal _DX11_
--

**Review by basisbit — APPROVED** [review]

**Pull request merged**
