### PR TITLE
Anst/improvements

### LINKED ISSUE #324: Lyrics are cropped on Android (Google Pixel 6)
Issue type: Bug report

### Actual behaviour
Lyrics in "bubbles" are cropped on a Google Pixel 6 phone (Android) even with only one player

Screenshot_20220902-234902

### Expected behaviour
See the full height of the lyrics in the bubbles when only one player is selected

### Details
Provide some additional information:

- UltraStar Play version: v0.7.0
- Operating System + version: Android 13

### LINKED ISSUE #337: SVG images do not use anti-aliasing
### Actual behaviour
Although UltraStar Play uses vector graphics, they are rendered with hard edges. This looks a little bit pixelated.

Example screenshots from a high DPI screen:
2022-11-16 15_03_49-help

2022-11-16 15_49_17-b_w

In comparison, text is rendered smoothly:
2022-11-16 15_03_58-text

### Expected behaviour
The vector graphics should look sharp and smooth.

### Details
Sadly, Unity's UI Toolkit does not yet apply anti-aliasing to vector graphics. See this [forum thread](https://forum.unity.com/threads/anti-aliasing-for-mesh-rendering-at-runtime.935213/#post-7901122).

A workaround could be to first render to a RenderTexture then apply anti-aliasing to this texture via a the scene camera.

However, this is a pretty cumbersome workaround. I'd rather wait for Unity to apply anti-aliasing to vector graphics in UI Toolkit.

- UltraStar Play version: 0.7.0

### PR DESCRIPTION
**Pull request by achimmihca**
### What does this PR do?

A bunch of fixes and improvements.

**Upgrade Unity**
- I upgraded to latest Unity, which is an alpha version but worked flawlessly for me.
- This finally fixes the stupidity with backslashes being interpreted as escape character in labels
    - Thus, paths with backslash can now be entered normally and do not need to be replaced anymore.
- This fixes ellipsis on multiline labels
    - For example, song title in song select scene are now abbreviated with ... if there is not enough space
- This improves some of Unity's tooling, e.g., the UI Builder

**Song issue dialog**
- The The SongLibraryOptionsScene has a new button to open a song issues dialog.
- The dialog lists issues in song files. Errors and warnings are listed separately.
    - Errors are issues where the song could not be loaded and will not be shown in song select. For example: unsupported audio file, missing required tag in song file
- The SongMetaManager collects all song issues. The parse method etc. have been extended accordingly.
- If there are song issues, then this is also shown as hint on the settings button 

**Song parsing**
- An empty tag value does not count as issue anymore. Instead, it is treated as `empty string` or `0` value.
- Spaced around tag key and tag value is now trimmed.
- I added tests for this new behaviour.

**Song folder checks**
- A warning is shown when a song folder is a duplicate of another folder
    -  This can also be the case, when they differ syntactically, e.g. by using `../` in the path or a trailing slash
- A warning is shown when a song folder is a subfolder of another song folder 

**Simpler download scene UI**
- The download scene UI has a dropdown button which opens an overlay with available song archive urls.
    - A short description is shown for each url.
- The song archive urls are loaded from JSON file.

**UltraStar song info**
- The SongLibraryOptionsScene options has a new button to open a help dialog.
- The dialog explains most important info about the song format, how to add, create, and download songs.
    - This is the stuff from our [FAQ ](https://github.com/UltraStar-Deluxe/Play/wiki/Frequently-Asked-Questions-(FAQ)) that is asked the most.

**Font Icons**
- instead of svg files, the Material Design Icons and Bootstrap Icons have been integrated as font file
- Therefor, new VisualElements named `FontIcon` (base class) `MaterialIcon` and `BootstrapIcon` have been added. 
    -  Icons can be changed just by setting their `icon` property.
    - For example, "help_outline" can be used to show [this icon](https://fonts.google.com/icons?selected=Material+Icons:help_outline:).
- Besides being much easier too use, this also fixes the problem of missing anti-aliasing #337 
- I tried to replace all pixel icons with these font icons or svg icons.
- Further, I replaced the leading-player-icon with [this one](https://publicdomainvectors.org/en/free-clipart/Golden-royal-crown/83935.html). Before, the icon was boring.

**Layout and styles**
- I refactored some styling.
    - For example, buttons do not always apply a fix width, margin, padding. Instead, this can be done manually where needed.
    - In the future, I want to integrate something like Bootstrap or TailwindCSS, which provide a set of reusable styling classes.
- Buttons use `--control-width` as `min-width` now. This has the advantage that they can grow large if needed (depending on translated text)
- The artist label and song title label have a more dynamic size. If there is a long name, the label gets smaller.

**New logo**
- The new logo is used and also shown in the main scene.

**Particle effect when hitting golden notes**
- When the player hits golden notes, then some silver stars are spawned.
    - I took inspiration for this from Vocaluxe.

**Lyrics are not cropped anymore**
- I set `overflow: visible;` on notes to fix #324
- Further, the font-size is calculated dynamically. It is not perfect, but better than before.

**Show static lyrics with scrolling note stream**
- The lyrics box at the top/bottom can now be shown together with the scrolling note stream lyrics
- "lyrics on note" vs. "lyrics in top/bottom box" can be configured independently
    - This replaces the dedicated lyrics bar at the bottom of each player's UI when using the scrolling note stream

**"bad" sentence rating is not shown anymore**
- I think positive feedback when players are good is better than negative feedback when they are bad.
    - Thus, the "bad" sentence rating is not shown anymore, no sentence rating is shown in this case. The other, positive sentence ratings are shown as before.
- relates to #304

**Song started statistic**
- A song counts as started only if it is played for some seconds or half of the song.
- I made the experience that I start a song only to notice that I don't like it (either the music or the notes are not well placed).
    - In such a case, I do not want to count this as "started" or "canceled", it should just be ignored.

**Show up to 3 player notes in time bar**
- The time bar is at the bottom of the sing scene. It shows where players have lyrics.
- For up to 3 players, their lyrics positions are shown individually.
- For more than 3 players there is not enough space in the time bar. In this case all lyrics are shown together in a neutral color.

**Kickstarter info dialog**
- The main scene shows a dialog with info about the upcoming Kickstarter.
- The dialog is shown once per start, until the Kickstarter ended.
- This will be removed after the Kickstarter.

### Closes Issue(s)

close #337 
close #324

### Additional Notes

Sorry for the hugeness of this PR. I just wanted to fix all this stuff before the upcoming Kickstarter.

### CODE REVIEW

**Comment by achimmihca** [comment]
Screenshots: 
2022-11-19 18_16_37-UltraStar Play
2022-11-19 18_16_51-UltraStar Play
2022-11-19 18_17_02-UltraStar Play
2022-11-19 18_17_10-UltraStar Play
2022-11-19 18_17_48-UltraStar Play
2022-11-19 18_19_17-UltraStar Play
2022-11-19 18_23_21-UltraStar Play
2022-11-19 18_23_52-UltraStar Play
golden-note-hit-effect

2022-11-19 18_14_29-UltraStar Play

**Comment by achimmihca** [comment]
I just noticed that there are no docker images for Unity alpha versions. Thus, the GitHub action cannot be upgraded to the newest version... 
But maybe the tests will work with both versions.

**Comment by achimmihca** [comment]
@basisbit , I want to merge this stuff monday to have a more polished version for the Kickstarter.
So it would be nice if you could review this soon.
Again, sorry for the hugeness of this PR.

**Comment by achimmihca** [comment]
There is now also a help dialog for mic configuration:

2022-11-20 21_13_46-UltraStar Play

**Review by basisbit — APPROVED** [review]
This was a lot. thanks for your continuous work!

**Pull request merged**
